<a href="https://colab.research.google.com/github/rauniyarmanish563-bot/class-works/blob/main/ones%20array%20array%20in%20numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
# Ones array
array1 = np.ones((4,3))
print(array1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [17]:
# ones arrrat with int datatype
array2 = np.ones((2,3,5) ,dtype = int)
print(array2)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]
