<a href="https://colab.research.google.com/github/rauniyarmanish563-bot/class-works/blob/main/zeros%20array%20in%20numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
# array creation in numpy
array3 = np.zeros((3,5))
print(array3)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [14]:
# array creation in numpy
array4 = np.zeros((4,5) , dtype = 'int')
print(array4)


[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [15]:
array5 = np.zeros((3,6,2) , dtype = 'int')
print(array5)


[[[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]]
